services:
  backend:
    build: 
      context: ./backend
    ports:
      - "3000:3000"
    container_name: backend
  
  frontend:
    build: 
      context: ./frontend
    ports:
      - "3500:80"
    depends_on:
      - backend
    container_name: frontend


    # dckr_pat_BigLMcJr-dE-0UpeeT6YTOBf_M4